title: SilenceOntheWire
description: > # this means to ignore newlines until "baseurl:"
  SilenceOntheWire - Twoje wrota do cyfrowej transformacji
site.title: SilenceOntheWire

sass:
    style: compressed


